// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.send("hello world");
  });

  server = app.listen(3000, function() {
    console.log("Server is running on port 3000");
    return "hello";
  });

}).call(this);
